Fix: Upgrade to react 18
optimizely/react-sdk pull request #159
Opened 2022-04-27 07:04 UTC by shaharyar123

## Summary
Updated the react SDK version from 16 to 18, to be compatible with v18 apps.

2022-05-17 23:29 UTC, zashraf1985 requested changes
Looks Great! Just two minor change requests

2022-05-17 23:29 UTC, zashraf1985 commented on .github/workflows/integration_test.yml
> -      run: |
This looks like an unnecessary change. can you re add the space here so that it does not appear in the PR diff

2022-05-17 23:29 UTC, zashraf1985 commented on src/hooks.spec.tsx
> +      await waitFor(() => expect(screen.getByTestId('result')).toHaveTextContent('null|false|false'));
Can you add the `// initial render` comment here again

2022-05-17 23:29 UTC, zashraf1985 commented
@opti-jnguyen Can you take a look when you get some time.

2022-05-19 18:18 UTC, zashraf1985 approved these changes
LGTM! Great work @shaharyar123

2022-05-31 15:51 UTC, opti-jnguyen approved these changes
Seems fine when testing locally - LGTM!

2022-05-31 18:00 UTC, merged