[FSSDK-9871] Hook for track events
optimizely/react-sdk pull request #268
Opened 2024-07-08 15:52 UTC by junaed-optimizely

## Summary
- A functional approach to track events.
- `useTrackEvents` hook is exposed similar to the existing `useDecision` hook.

## Test plan
New test cases have been added to support the new functionality

## Issues
[FSSDK-9871](https://jira.sso.episerver.net/browse/FSSDK-9871)

2024-07-08 18:33 UTC, mikechu-optimizely requested changes
Great work. Thanks. I do not see any show-stoppers, but please review the following suggestions 👇

2024-07-08 18:33 UTC, mikechu-optimizely commented on src/index.ts
> +export { useFeature, useExperiment, useDecision, useTrackEvents } from './hooks';
NIT: I might follow the singular naming for your new hook, `useTrackEvent`

2024-07-08 18:33 UTC, mikechu-optimizely commented on src/hooks.ts
> +interface UseTrackEvents {
NIT: singular naming maybe?

```suggestion
interface UseTrackEvent {
```

2024-07-08 18:33 UTC, mikechu-optimizely commented on README.md
🔔 Reminder: update developer docs.

2024-07-08 18:33 UTC, mikechu-optimizely commented on src/hooks.spec.tsx
Please update each of these files' Copyright years.

2024-07-09 12:02 UTC, junaed-optimizely commented on README.md
Ok. Thats going to be an after-release task.

2024-07-09 15:43 UTC, mikechu-optimizely approved these changes
LGTM

2024-07-09 15:50 UTC, merged